### PR TITLE
Add author attribution articles and real name in posts

### PR DESCRIPTION
**Pull request by z64**

### CODE REVIEW

**Comment by z64** [comment]
Anyone who would like their real name in posts, just let me know and I'll add it to this PR. Or commit it yourself to this branch.

**Review by ar1a — APPROVED** [review]
Looks good

**Comment by unleashy** [comment]
Add me as "Eduardo Fernandes" biatch

**Comment by ar1a** [comment]
please commit more things when i am about to commit more things please

**Pull request closed without merging**
